name: Automation tasks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Documentation:
    runs-on: ubuntu-latest

    permissions:   #  needed so push works
      contents: write

    steps:
      - name: Get workspace 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  #  required to push commits

      - name: Build documentation
        run: |
          sudo apt update
          sudo apt install -y doxygen=1.14.0
          cd ${{ github.workspace }}/docs/Kraken
          rm -rf ./html
          ls
          doxygen Doxyfile

      - name: Commit and push docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/docs/Kraken/html/*
          git commit -m "chore: update Doxygen docs [skip ci]" || echo "No changes to commit"
          git push
